In [10]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/input-re/Prompt Val 100.xlsx
/kaggle/input/input-re/Prompt Train 800.xlsx
/kaggle/input/input-re/Prompt Test 101.xlsx
/kaggle/input/uuuuuu/Google Translated Train.csv
/kaggle/input/uuuuuu/Google Translated test.csv
/kaggle/input/uuuuuu/Google Translated Val.csv
/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_val.csv
/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_train.csv
/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_test.csv

In [11]:
pip install googletrans==4.0.0-rc1

Requirement already satisfied: googletrans==4.0.0-rc1 in /opt/conda/lib/python3.10/site-packages (4.0.0rc1)
Requirement already satisfied: httpx==0.13.3 in /opt/conda/lib/python3.10/site-packages (from googletrans==4.0.0-rc1) (0.13.3)
Requirement already satisfied: certifi in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.8.30)
Requirement already satisfied: hstspreload in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.11.1)
Requirement already satisfied: sniffio in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Requirement already satisfied: chardet==3.* in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: idna==2.* in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in /opt/conda/lib/python3.10/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in /opt/conda/lib/python3.10/site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.0)
Requirement already satisfied: h2==3.* in /opt/conda/lib/python3.10/site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /opt/conda/lib/python3.10/site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /opt/conda/lib/python3.10/site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
train=pd.read_excel('/kaggle/input/input-re/Prompt Train 800.xlsx',usecols=['text','los_label'])
val=pd.read_excel('/kaggle/input/input-re/Prompt Val 100.xlsx',usecols=['text','los_label'])
test=pd.read_excel('/kaggle/input/input-re/Prompt Test 101.xlsx',usecols=['text','los_label'])

In [13]:
train

                                                  text  los_label
0    CHIEF COMPLAINT: Dyspnea on exertion and worse...          1
1    CHIEF COMPLAINT: shortness of breath\n\nPRESEN...          2
2    CHIEF COMPLAINT: \n\nPRESENT ILLNESS: This is ...          1
3    CHIEF COMPLAINT: Chest Pain\n\nPRESENT ILLNESS...          1
4    CHIEF COMPLAINT: Transfer from [**Hospital 613...          3
..                                                 ...        ...
795  CHIEF COMPLAINT: bright red blood per rectum\n...          1
796  CHIEF COMPLAINT: Sternal drainage\n\nPRESENT I...          2
797  CHIEF COMPLAINT: Admitted for TIPS\n\nPRESENT ...          1
798  CHIEF COMPLAINT: Status-post MVC with polytrau...          2
799  CHIEF COMPLAINT: Bloody diarrhea\n\nPRESENT IL...          2

[800 rows x 2 columns]

In [14]:
val

                                                 text  los_label
0   CHIEF COMPLAINT: Traumatic Brain Injury\n\nPRE...          2
1   CHIEF COMPLAINT: GI bleed\n\nPRESENT ILLNESS: ...          2
2   CHIEF COMPLAINT: s/p [**2081**]0-25 ft\n\nPRES...          2
3   CHIEF COMPLAINT: low HCT\n\nPRESENT ILLNESS: P...          1
4   CHIEF COMPLAINT: Elective cardiac catheterizat...          1
..                                                ...        ...
95  CHIEF COMPLAINT: new acute low back pain w/ bi...          3
96  CHIEF COMPLAINT: Syncope\n\nPRESENT ILLNESS: 5...          1
97  CHIEF COMPLAINT: s/p ? Fall, found down\n\nPRE...          3
98  CHIEF COMPLAINT: BRBPR\n\nPRESENT ILLNESS: Hx ...          0
99  CHIEF COMPLAINT: \n\nPRESENT ILLNESS: The pati...          3

[100 rows x 2 columns]

In [15]:
test

                                                  text  los_label
0    CHIEF COMPLAINT: Left flank pain\n\nPRESENT IL...          2
1    CHIEF COMPLAINT: Abdominal pain.\n\nPRESENT IL...          3
2    CHIEF COMPLAINT: Status post wall falling onto...          3
3    CHIEF COMPLAINT: SOB, chest pain\n\nPRESENT IL...          1
4    CHIEF COMPLAINT: dyspnea, hypoxemia\n\nPRESENT...          2
..                                                 ...        ...
96   CHIEF COMPLAINT: Fever.\n\nPRESENT ILLNESS: Th...          3
97   CHIEF COMPLAINT: Back and leg pain\n\nPRESENT ...          2
98   CHIEF COMPLAINT: Back and leg pain\n\nPRESENT ...          1
99   CHIEF COMPLAINT: sepsis\n\nPRESENT ILLNESS: 61...          1
100  CHIEF COMPLAINT: Chest burning and dyspnea on ...          3

[101 rows x 2 columns]

In [ ]:
from googletrans import Translator

# Initialize the translator
translator = Translator()

try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
        print("Oops!  That was no valid number.  Try again...")

len(train.loc[0,'text'])

from tqdm import tqdm
final=[]
print("10000-15000")
num=0
for text in tqdm(train.loc[29082:29082,'text']): #text=train['text'][0:3]
    num+=1
    print(num)
    initial=[]
    start=0
    finish=5000
    for i in range(9999999999):
        try:
            translation=translator.translate(text, src='en', dest='bn')
            translation=translator.translate(text[start:finish], src='en', dest='bn')
            initial.append(translation.text)
            start=finish
            finish=finish+5000
        except TypeError:
        #translation=pipe(text[start:finish],num_workers=-1)[0]['translation_text']
        #if translation=='▪ (w-BE)':
            final.append(" ".join(initial))
            break
        #else:
            #initial.append(translation)
            #start=finish
            #finish=finish+632
len(final)

#trans=pd.DataFrame()
#trans['machine']=final
#trans.to_csv('First 10000:15000 Machine Translated Train LOS')

# MAIN

In [ ]:
from tqdm import tqdm
final=[]
print("Google Train")
num=0
for text in tqdm(train['text'][0:]): #text=train['text'][0:3]
    from googletrans import Translator
    translator = Translator()
    num+=1
    print(num)
    initial=[]
    start=0
    finish=5000
    for i in range(9999999999):
        try:
            translation=translator.translate(text, src='en', dest='bn')
            final.append(translation.text)
            print('no Execpt')
            break
        except TypeError:
            print('first Execpt')
            try:
                translation=translator.translate(text[start:finish], src='en', dest='bn')
                initial.append(translation.text)
                start=finish
                finish=finish+5000
            except TypeError:
                print('2nd Execpt')
                final.append(" ".join(initial))
                break
        #translation=pipe(text[start:finish],num_workers=-1)[0]['translation_text']
        #if translation=='▪ (w-BE)':
        #else:
            #initial.append(translation)
            #start=finish
            #finish=finish+632
len(final)

trans=pd.DataFrame()
trans['machine']=final
trans.to_csv('Google Translated Train.csv',index=False)

In [ ]:
from tqdm import tqdm
final=[]
print("Google Val")
num=0
for text in tqdm(val['text'][0:]): #text=train['text'][0:3]
    from googletrans import Translator
    translator = Translator()
    num+=1
    print(num)
    initial=[]
    start=0
    finish=5000
    for i in range(9999999999):
        try:
            translation=translator.translate(text, src='en', dest='bn')
            final.append(translation.text)
            print('no Execpt')
            break
        except TypeError:
            print('first Execpt')
            try:
                translation=translator.translate(text[start:finish], src='en', dest='bn')
                initial.append(translation.text)
                start=finish
                finish=finish+5000
            except TypeError:
                print('2nd Execpt')
                final.append(" ".join(initial))
                break
        #translation=pipe(text[start:finish],num_workers=-1)[0]['translation_text']
        #if translation=='▪ (w-BE)':
        #else:
            #initial.append(translation)
            #start=finish
            #finish=finish+632
len(final)

trans=pd.DataFrame()
trans['machine']=final
trans.to_csv('Google Translated Val.csv',index=False)

In [ ]:
from tqdm import tqdm
final=[]
print("Google Test")
num=0
for text in tqdm(test['text'][0:]): #text=train['text'][0:3]
    from googletrans import Translator
    translator = Translator()
    num+=1
    print(num)
    initial=[]
    start=0
    finish=5000
    for i in range(9999999999):
        try:
            translation=translator.translate(text, src='en', dest='bn')
            final.append(translation.text)
            print('no Execpt')
            break
        except TypeError:
            print('first Execpt')
            try:
                translation=translator.translate(text[start:finish], src='en', dest='bn')
                initial.append(translation.text)
                start=finish
                finish=finish+5000
            except TypeError:
                print('2nd Execpt')
                final.append(" ".join(initial))
                break
        #translation=pipe(text[start:finish],num_workers=-1)[0]['translation_text']
        #if translation=='▪ (w-BE)':
        #else:
            #initial.append(translation)
            #start=finish
            #finish=finish+632
len(final)

trans=pd.DataFrame()
trans['machine']=final
trans.to_csv('Google Translated test.csv',index=False)

##

## Dataset

In [18]:
google_train=pd.read_csv('/kaggle/input/uuuuuu/Google Translated Train.csv')
google_val=pd.read_csv('/kaggle/input/uuuuuu/Google Translated Val.csv')
google_test=pd.read_csv('/kaggle/input/uuuuuu/Google Translated test.csv')

In [19]:
google_train['los_label']=train['los_label']
google_val['los_label']=val['los_label']
google_test['los_label']=test['los_label']

In [23]:
google_train

                                               machine  los_label
0    প্রধান অভিযোগ: পরিশ্রম এবং বুকে ব্যথা অবনতি সম...          1
1    প্রধান অভিযোগ: শ্বাসকষ্ট\n\nবর্তমান অসুস্থতা: ...          2
2    প্রধান অভিযোগ:\n\nবর্তমান অসুস্থতা: এটি একটি 7...          1
3    প্রধান অভিযোগ: বুকে ব্যথা\n\nবর্তমান অসুস্থতা:...          1
4    প্রধান অভিযোগ: পোর্টেক্স ট্র্যাচোস্টোমির জন্য ...          3
..                                                 ...        ...
795  প্রধান অভিযোগ: মলদ্বার প্রতি উজ্জ্বল লাল রক্ত\...          1
796  প্রধান অভিযোগ: কঠোর নিকাশী\n\nবর্তমান অসুস্থতা...          2
797  প্রধান অভিযোগ: টিপসের জন্য ভর্তি\n\nবর্তমান অস...          1
798  প্রধান অভিযোগ: পলিট্রোমা সহ স্ট্যাটাস-পোস্ট এম...          2
799  প্রধান অভিযোগ: রক্তাক্ত ডায়রিয়া\n\nবর্তমান অ...          2

[800 rows x 2 columns]

In [24]:
google_train.to_csv('Google Translated train final.csv',index=False)
google_val.to_csv('Google Translated val final.csv',index=False)
google_test.to_csv('Google Translated test final.csv',index=False)

In [ ]:
#g=pd.read_csv('/kaggle/working/First 10000:15000 Machine Translated Train LOS')

In [ ]:
#len(g.loc[1,'machine'])

In [ ]:
#train.loc[29082,'text']

In [ ]:
#final[1]

In [ ]:
#print(len(final[0]))
#final

In [ ]:
#len(train.loc[0:5000,'text'])

for text in train['text'][:3]:
    #print(text,end="\n \n")
    print(type(text))

from tqdm import tqdm
final=[]
print("10000-15000")
num=0
for text in tqdm(train['text'][:3]): #text=train['text'][0:3]
    initial=[]
    start=0
    finish=632
    translation=translator.translate(text, src='en', dest='bn')
    final.append(translation.text)
   
len(final)

In [ ]:
#train.loc[29082,'text']

y=(train['text'].apply(len)==22431).values

for i in range(len(y)):
    if y[i]==True:
        print(i)
        break

final[1]

# 632 ta kore

text=train.loc[29082,'text']


text=' '

# Translate to Bengali
translated = translator.translate(text, src='en', dest='bn')

# Print the translated text
print("Original Text:", text)
print("Translated Text:", translated.text)

len(translated.text)