In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_val.csv
/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_train.csv
/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_test.csv
/kaggle/input/los-translated-opus-mt-en-bn-010000/First 15000_20000 Machine Translated Train LOS
/kaggle/input/los-translated-opus-mt-en-bn-010000/First 5000_10000 Machine Translated Train LOS
/kaggle/input/los-translated-opus-mt-en-bn-010000/First 10000_15000 Machine Translated Train LOS
/kaggle/input/los-translated-opus-mt-en-bn-010000/First 28000_~ Machine Translated Train LOS
/kaggle/input/los-translated-opus-mt-en-bn-010000/First 0_5000 Machine Translated Train LOS
/kaggle/input/los-translated-opus-mt-en-bn-010000/Opus Mt 20000_25000 En-Bn Train LOS
/kaggle/input/los-translated-opus-mt-en-bn-010000/First 25000_28000 Machine Translated Train LOS
/kaggle/input/opus-val-all/Validation all Machine Translated  LOS
/kaggle/input/opus-test-07500/Test 6000_7500 Machine Translated  LOS
/kaggle/input/opus-test-07500/Test 4000_6000 Machine Translated  LOS
/kaggle/input/opus-test-07500/Test 7500_ Machine Translated  LOS
/kaggle/input/opus-test-07500/Test 0_4000 Machine Translated LOS

In [2]:
los_train=pd.read_csv('/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_train.csv')
los_val=pd.read_csv('/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_val.csv')
los_test=pd.read_csv('/kaggle/input/los-of-stay/LOS/LOS_WEEKS_adm_test.csv')

# Val

In [3]:
translated_opus_val=pd.read_csv('/kaggle/input/opus-val-all/Validation all Machine Translated  LOS')

In [9]:
translated_opus_val['los_label']=los_val['los_label']

In [13]:
#los_val['los_label']
translated_opus_val.drop('Unnamed: 0',axis=1,inplace=True)
translated_opus_val.rename(columns={'machine':'text'},inplace=True)

In [23]:
translated_opus_val.to_csv('Mimic Los Bangla Val.csv')

In [78]:
print(len(translated_opus_val))
len(los_val)

4391

4391

-------------------------------------------------

-------------------------------------------

----------------------------------------------------------------------

# Test

In [26]:
x=pd.read_csv('/kaggle/input/opus-test-07500/Test 0_4000 Machine Translated LOS')
x1=pd.read_csv('/kaggle/input/opus-test-07500/Test 4000_6000 Machine Translated  LOS')
x2=pd.read_csv('/kaggle/input/opus-test-07500/Test 6000_7500 Machine Translated  LOS')
x3=pd.read_csv('/kaggle/input/opus-test-07500/Test 7500_ Machine Translated  LOS')

In [29]:
test=pd.concat([x,x1,x2,x3], ignore_index=True).drop('Unnamed: 0',axis=1)

In [31]:
test['los_label']=los_test['los_label']

In [39]:
i=234
print(test.loc[i,'machine'])
los_test.loc[i,'text']

প্রধান অভিযোগ: হাইপোটেনশন, জ্বর বিদ্যমান অসুস্থতা: ইতিহাস এবং শারীরিকতা ইকুবাসী, ডঃ [** প্রথম নাম (শিক্ষা দেওয়া হয়) [**] [শিক্ষা দেওয়া] [**] এটি ৪৯ বছর বয়সী পুরুষ যার ইতিহাস ছিল আঞ্চোপলাসিয়া, হিটসন, ডাইসটোলিক চক্ফ, দীর্ঘস্থায়ী লিম্ফিডেমা, শারীরিক নিদ্রা আপেনা, যা ছিল। [*Hostpital1 18*] চিকিৎসার পর থেকে [**Hospitial1] শ্বাস নিষ্পত্তি, নিউমোনিয়া এবং সেলুলিটিস এখন জ্বর এবং হাইপোটেনশন দিয়ে উপস্থাপিত হয়েছে। [*Hostpital1 49145*], রোগীকে ফেব্রিল বলে মনে করা হয় এবং ৭০ সালে systolicy এর সাথে রক্তচাপ পাওয়ার জন্য তাকে হস্তান্তর করা হয়। [**hospital 1263*] হাসপাতাল যেখানে তাকে ১.৯ এর ক্রিটিনিনের (বাইবেল লাইন ০.৫-০.৭) সাথে তীব্র পুনর্গঠন ব্যর্থতার বিষয়ে উল্লেখ করা হয়েছিল এবং তিনি [**3-8**] লিটার লিটারস ডিহাইডের জন্য পান, systolic 90 এর রক্তের চাপের উন্নতির ফলে। এরপর তাকে [*hospital1*] প্রতি রিকুতে স্থানান্তরিত করা হয়। পরিবারের মধ্যে সবচেয়ে সাম্প্রতিক চিকিৎসা এখানে দেওয়া হয়েছে। তার শেষ ভর্তিকালে, রোগী [১] হাইপারকার্বেটিক শ্বাসপ্রশ্বাস ব্যর্থতার জন্য ১৯৬৯২*] ইনটুব্লিউটে যুক্ত [১]। ইনস্টিটিউশনের পর অসংখ্য গোপনীয়তার কারণে, রোগীর সাথে ভ্যানকমিসিন, আলেফ্লোক্সেকিন, মিটাররনাইডোলের সাথে ব্যবহার করা হয়েছিল [*তারি ১] ৭৯৪৩৫*] এবং অনুমানকৃত বায়ুপ্রবাহী নিউমোনিয়ার জন্য ৮ দিনের একটি কোর্সের কাজ সম্পন্ন করে। এছাড়াও একটি প্রশ্নও ছিল যা সম্ভবত অ্যান্টিবায়োটিকের উপরও আচ্ছাদিত ছিল। এছাড়াও, রোগীর বিরোধী-হাইপারটেনিভ শাসনামলে নাটকীয়ভাবে উন্নীত করা হয়েছিল। তার মূল পুনর্সাক্ষাৎ। গিমেন কেবল মেটপ্রোলোল ২৫মগ [**হোস্পিটাল১**) নিয়ে গঠিত ছিল। যখন তিনি দ্বিধাগ্রস্ত ছিলেন, তিনি তার বাড়ির শাসনামলে হাইপারটেনসিভ ছিলেন, তাই প্রাথমিকভাবে ১২.৫mg tid এর একটি ডোসে যোগ করা হয়, তারপর ক্রমাগত ৩৭.৫mg tid পর্যন্ত উন্নীত করা হয়। এরপর তিনি প্রতিদিন লিসিনোপ্লাগ ৪০.এ রূপান্তরিত হন। আগের ভর্তিতে টেরাজোসিন থেকে শুরু করে, এবং ডক্সোজিনকে পরিবর্তন করা হয়েছে [*Hospitial1 154544*)। চিকিৎসা ইতিহাস: Achondroplasia htnal stenoss s/p back conspecienty limphedama se justicture: #. docaste 100mg [**hopital1] #. enoxaprin 40mg sc Miciconazol 2% pouder [**hospital1 **] #. senna po qhs #. Sarna Lotoonion on the real posterior q6h prn #. albutertool q6h prn #. laclushlos 30ml q6h prn #. Mym 30 ml po prn #. ternorazole 500mgiv # Vanycin # doxazosin 1mg qhs #. lisinpril 20mg [**hospital1**] # metoprol 25mg [**Hospital1] Allie: Peniclins duistins: Icu camption secription in the search: family: form

"CHIEF COMPLAINT: Hypotension, fevers\n\nPRESENT ILLNESS: History and physical is as per admitting ICU resident, Dr. [**First Name (STitle) **] [**Name (STitle) 6133**]  This is a 49 year-old male with a history of achondroplasia, HTN, diastolic CHF, chronic lymphedema, obstructive sleep apnea, who was recently discharged from [**Hospital1 18**] after treatment hypercapneic respiratory failure, pneumonia and cellulitis now presents with fevers and hypotension. While at [**Hospital1 49145**], patient was noted to be febrile and found to have blood pressure with systolic in 70s. He was transferred to [**Hospital 1263**] hospital where he was noted to have acute renal failure with creatinine of 1.9 (baseline 0.5-0.7) and he received [**3-8**] litres IV fluids for presumed dehydration, with improvement in the blood pressure to systolic 90s. He was then transferred to [**Hospital1 18**] per request of the family, given his recent treatment here. . During his last admission, patient [**Last Name (un) 19692**] intubated in ED for hypercarbic respiratory failure. Due to copious secretions after intubation, patient was treated with Vancomycin, levofloxacin, metronidazole from [**Date range (1) 79435**] and completed an 8-day course for presumed ventilator-associated pneumonia. There was also a question of cellulitis that was presumably also covered by above antibiotics. . Also of note, patient's anti-hypertensive regimen was dramatically uptitrated while he was intubated. His original regimen consisted only of metoprolol 25mg [**Hospital1 **]. While he was intubated, he was hypertensive on his home regimen, so captopril was added, initially at a dose of 12.5mg TID, then continually uptitrated to 37.5mg TID. He was then changed to lisinopril 40mg daily prior to discharge. He was also started on terazosin on the previous admission, and had been changed to doxazosin at [**Hospital1 15454**]. .\n\nMEDICAL HISTORY: achondroplasia HTN spinal stenosis s/p back surgery chronic lymphedema obesity\n\nMEDICATION ON ADMISSION: #. Docusate 100mg [**Hospital1 **] #. Enoxaparin 40mg SC daily #. Miconazole 2% powder [**Hospital1 **] #. Senna PO qHS #. Sarna lotion to right lateral posterior thigh daily #. Albuterol q6H PRN #. Lactulose 30ml q6H PRN #. MOM 30 ML PO PRN #. Metronidazole 500mg IV #. Vancomycin 1gram q12H #. Ceftazidime ordered but held due to pencillin allergy following home medications were held #. Doxazosin 1mg qHS #. Lisinopril 20mg [**Hospital1 **] #. Metoprolol 25mg [**Hospital1 **]\n\nALLERGIES: Penicillins\n\nPHYSICAL EXAM: At time of ICU admission Physical Exam was as follows:\n\nFAMILY HISTORY: Unknown\n\nSOCIAL HISTORY: Unknown"

In [43]:
test.rename(columns={'machine':'text'},inplace=True)

In [49]:
test

                                                   text  los_label
0     প্রধান অভিযোগ: syncopeal পর্ব থেকে পড়ে, মুখের...          3
1     প্রধান অভিযোগ: অ্যাবডোমিনাল ব্যথা বর্তমান অসুস...          1
2     প্রধান অভিযোগ: বর্তমান অসুস্থতা: pcp: [**name1...          3
3     প্রধান অভিযোগ: বর্তমান অসুবিধা: ৭৩ y/ও মহিলা য...          0
4     প্রধান অভিযোগ: ডায়রিয়া, পঞ্চায়েটিক মাথার ভর...          2
...                                                 ...        ...
8792  প্রধান অভিযোগ: শ্বাসপ্রশ্বাস দুর্দশা বর্তমান অ...          2
8793  প্রধান অভিযোগ: মাথাব্যথা, মমব্লালি কথাবার্তা ব...          2
8794  প্রধান অভিযোগ: অ্যানামিয়াম, আব্ডোমিনাল ব্যথা।...          3
8795  প্রধান অভিযোগ: আব্ডোমিনাল ব্যথা / বমি করা বর্ত...          0
8796  প্রধান অভিযোগ: ক্যাটাটোনিয়া বর্তমান অসুস্থতা:...          2

[8797 rows x 2 columns]

In [50]:
test.to_csv('Mimic Los Bangla Test.csv')

In [47]:
translated_opus_val

                                                   text  los_label
0     প্রধান অভিযোগ: অনিউরিজম বর্তমান অসুস্থতা: ms. ...          0
1     প্রধান অভিযোগ: বৌদ্ধতা, বর্তমান অসুস্থতা: [৯০*...          2
2     প্রধান অভিযোগ: মাথাব্যথা, অপ্রতিরোধী। চিকিৎসা ...          3
3     প্রধান অভিযোগ: আব্ডোমিনাল ব্যথা এবং বমি করা x2...          1
4     প্রধান অভিযোগ: মৃদু ডিস্পনিয়া বর্তমান অসুস্থত...          2
...                                                 ...        ...
4386  প্রধান অভিযোগ: ডান দিকের ঠোঁট অশ্লীলতা, বর্তমা...          1
4387  প্রধান অভিযোগ: বুকের ব্যথা বর্তমান অসুস্থতা: প...          2
4388  প্রধান অভিযোগ: বাম দিকের মস্তিষ্কের অসুখ বর্তম...          3
4389  প্রধান অভিযোগ: বুকে এক্স-রায় এবং শ্বাসের স্বল...          1
4390  প্রধান অভিযোগ: বাঁধা নীফ্রোলিথিয়াসিস বর্তমান ...          2

[4391 rows x 2 columns]

------------------------------------------------

-------------------------------------------

---------------------------------------------

# Train

In [52]:
x1=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/First 0_5000 Machine Translated Train LOS')
x2=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/First 5000_10000 Machine Translated Train LOS')
x3=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/First 10000_15000 Machine Translated Train LOS')
x4=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/First 15000_20000 Machine Translated Train LOS')
x5=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/Opus Mt 20000_25000 En-Bn Train LOS')
x6=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/First 25000_28000 Machine Translated Train LOS')
x7=pd.read_csv('/kaggle/input/los-translated-opus-mt-en-bn-010000/First 28000_~ Machine Translated Train LOS')

In [62]:
train=pd.concat([x1,x2,x3,x4,x5,x6,x7],ignore_index=True).drop('Unnamed: 0',axis=1).rename(columns={'machine':'text'})

In [63]:
train['los_label']=los_train['los_label']

In [72]:
i=1777
print(train.loc[i,:])
los_train.loc[i,:]

text         প্রধান অভিযোগ: বর্তমান অসুস্থতা: [*****] [** শ...
los_label                                                    2
Name: 1777, dtype: object

id                                                      126652
text         CHIEF COMPLAINT: \n\nPRESENT ILLNESS: [**Known...
los_label                                                    2
Name: 1777, dtype: object

In [76]:
train.to_csv('Mimic Los Bangla Train.csv')

In [77]:
train

                                                    text  los_label
0      প্রধান অভিযোগ: প্রতিক্রিয়াশীলতা প্রধান [** প্...          0
1      প্রধান অভিযোগ: ক্লান্তি, বিস্তৃত তাচিকার্ডিয়া...          1
2      প্রধান অভিযোগ: বর্তমান অসুস্থতা: এটি ৫৮ বছর বয...          2
3      প্রধান অভিযোগ: বর্তমান অসুস্থতা: এটি ৫৩ বছর বয...          1
4      প্রধান অভিযোগ: বর্তমান অসুস্থতার কারণে শ্বাস ন...          2
...                                                  ...        ...
30416  প্রধান অভিযোগ: বর্তমানে অসুস্থতা: ৩৬ বছর বয়সী...          0
30417  প্রধান অভিযোগ: মানসিক অবস্থার পরিবর্তন: [** শে...          0
30418  প্রধান অভিযোগ: বুকের ব্যথা বর্তমান অসুস্থতা: ৮...          1
30419  প্রধান অভিযোগ: মর্যাদামৃত্যু, বর্তমান অসুস্থতা...          3
30420  প্রধান অভিযোগ: কাশির ক্ষয়ক্ষতির কারণ: বর্তমান...          3

[30421 rows x 2 columns]